"use client";
import { createContext,useContext,useEffect,useState } from "react";
import { seedClasses,seedRequests,seedStudents,seedTransactions,seedUsers } from "@/lib/seed";
import type { Role,SchoolClass,SchoolRequest,StaffUser,Student,Transaction } from "@/lib/types";
type Store={role:Role;setRole:(r:Role)=>void;students:Student[];classes:SchoolClass[];requests:SchoolRequest[];transactions:Transaction[];users:StaffUser[];addStudent:(v:Omit<Student,"id"|"status">)=>void;addClass:(v:Omit<SchoolClass,"id"|"students">)=>void;addRequest:(v:Pick<SchoolRequest,"subject"|"details"|"category">)=>void;evaluateRequest:(id:string,n:number)=>void;decideRequest:(id:string,a:boolean)=>void;addTransaction:(v:Omit<Transaction,"id"|"status"|"date">)=>void;decideTransaction:(id:string,a:boolean)=>void;addUser:(v:Pick<StaffUser,"name"|"email"|"role">)=>void;toggleUser:(id:string)=>void};
const C=createContext<Store|null>(null);const today=()=>new Intl.DateTimeFormat("fr-CD",{day:"2-digit",month:"short",year:"numeric"}).format(new Date());
export function Providers({children}:{children:React.ReactNode}){const[role,setRole]=useState<Role>("principal_admin");const[students,setStudents]=useState(seedStudents);const[classes,setClasses]=useState(seedClasses);const[requests,setRequests]=useState(seedRequests);const[transactions,setTransactions]=useState(seedTransactions);const[users,setUsers]=useState(seedUsers);const[ready,setReady]=useState(false);
useEffect(()=>{try{const s=localStorage.getItem("glory-house-store");if(s){const d=JSON.parse(s);setStudents(d.students??seedStudents);setClasses(d.classes??seedClasses);setRequests(d.requests??seedRequests);setTransactions(d.transactions??seedTransactions);setUsers(d.users??seedUsers)}}finally{setReady(true)}},[]);useEffect(()=>{if(ready)localStorage.setItem("glory-house-store",JSON.stringify({students,classes,requests,transactions,users}))},[ready,students,classes,requests,transactions,users]);
const value:Store={role,setRole,students,classes,requests,transactions,users,addStudent:v=>setStudents(a=>[{...v,id:`ELV-${a.length+487}`,status:"Actif"},...a]),addClass:v=>setClasses(a=>[{...v,id:`CLS-${a.length+1}`,students:0},...a]),addRequest:v=>setRequests(a=>[{...v,id:`DEM-${Date.now()}`,amount:null,status:"pending_finance",requestedBy:"Direction",createdAt:today()},...a]),evaluateRequest:(id,amount)=>setRequests(a=>a.map(x=>x.id===id?{...x,amount,status:"pending_admin"}:x)),decideRequest:(id,ok)=>setRequests(a=>a.map(x=>x.id===id?{...x,status:ok?"approved":"rejected"}:x)),addTransaction:v=>setTransactions(a=>[{...v,id:`TRX-${Date.now()}`,status:"pending",date:today()},...a]),decideTransaction:(id,ok)=>setTransactions(a=>a.map(x=>x.id===id?{...x,status:ok?"approved":"rejected"}:x)),addUser:v=>setUsers(a=>[{...v,id:`USR-${Date.now()}`,active:true},...a]),toggleUser:id=>setUsers(a=>a.map(x=>x.id===id?{...x,active:!x.active}:x))};return <C.Provider value={value}>{children}</C.Provider>}
export function useStore(){const v=useContext(C);if(!v)throw new Error("Store unavailable");return v}
